name: Generate Newman test report

on: push

permissions:
  contents: write

jobs:  
  test:
    runs-on: ubuntu-latest

    name: Run project tests

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ("latest" Version)
      uses: actions/setup-node@v4
      with:
        node-version: latest   # <-- use "latest" for the most recent Node.js version

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install Newman
      run: npm install -g newman

    - name: Install Newman Allure
      run: npm install -g newman-reporter-allure

    - name: Generate Newman Allure Report
      run: newman run -x ./test/Postman_collection/Test.postman_collection.json -e ./test/Postman_collection/Moovsmart.postman_environment.json -r allure --reporter-allure-export ./test/allure-results

    - name: Delete setup requests
      run: python ./test/post_process_allure/remove_by_tag.py
    
    - name: Allure Report action from marketplace 
      uses: simple-elf/allure-report-action@master 
      with: 
        allure_results: ./test/allure-results 
        allure_history: ./test/allure-history 
        keep_reports: 20

    

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v2 
      env: 
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages 
        PUBLISH_DIR: ./test/allure-history
      

