name: Generate Newman test report

on: push

permissions:
  contents: write

jobs:  
  test:
    runs-on: ubuntu-latest

    name: Run project tests

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ("latest" Version)
      uses: actions/setup-node@v4
      with:
        node-version: latest   # <-- use "latest" for the most recent Node.js version

    - name: Install Newman
      run: npm install -g newman

    - name: Install Newman Allure
      run: npm install -g newman-reporter-allure

    - name: Generate Newman Allure Report 1
      continue-on-error: true
      run: newman run ./test/Postman_collection/TC1_Registration.postman_collection.json -e ./test/Postman_collection/Moovsmart.postman_environment.json -r allure --reporter-allure-export ./test/allure-results
      
    - name: Generate Newman Allure Report 2
      continue-on-error: true
      run: newman run ./test/Postman_collection/TC2_Login.postman_collection.json -e ./test/Postman_collection/Moovsmart.postman_environment.json -r allure --reporter-allure-export ./test/allure-results
      
    - name: Generate Newman Allure Report 3
      continue-on-error: true
      run: newman run ./test/Postman_collection/TC3_Profile.postman_collection.json -e ./test/Postman_collection/Moovsmart.postman_environment.json -r allure --reporter-allure-export ./test/allure-results

    - name: Allure Report action from marketplace 
      uses: simple-elf/allure-report-action@master 
      with: 
        allure_results: ./test/allure-results 
        allure_history: ./test/allure-history 
        keep_reports: 20

    - name: Deploy report to Github Pages 
      if: always() 
      uses: peaceiris/actions-gh-pages@v2 
      env: 
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages 
        PUBLISH_DIR: ./test/allure-history
      

