name: Generate Newman test report

on: push

jobs:  
  test:
    runs-on: ubuntu-latest

    name: Run project tests

    steps:
    - name: Setup Node.js ("latest" Version)
      uses: actions/setup-node@v4
      with:
        node-version: latest   # <-- use "latest" for the most recent Node.js version

    # - name: Other steps …
